strict.perms: false
filebeat.inputs:
  - type: docker
    containers.ids: ['*']
    combine_partial: true

processors:
  - add_docker_metadata: ~

output.elasticsearch:
  hosts: ["http://host.docker.internal:9200"]

setup.kibana:
  host: "host.docker.internal:5601"


