version: '3.8'

services:
  api:
    build: .
    ports:
      - "5000:5000"
    volumes:
      # Mount data directory để persist routes.json
      - ./data:/app/data
    environment:
      - FLASK_ENV=production
    restart: unless-stopped
