version: '3.9'

services:
  # Template service (khuôn mẫu để tạo services mới)
  template:
    build: ./services/template
    ports:
      - "8000:8000"
    environment:
      - DEBUG=true
    labels:
      co.elastic.logs/enabled: "true"
      co.elastic.logs/json.keys_under_root: "true"
      co.elastic.logs/json.add_error_key: "true"
    restart: unless-stopped

  order:
    build: ./services/order
    ports:
      - "8001:8000"
    environment:
      - DEBUG=true
      - MONGODB_URI=mongodb+srv://BlueDuck2:Fcsunny0907@tpexpress.zjf26.mongodb.net/?retryWrites=true&w=majority&appName=TPExpress
      - MONGODB_DB=TPExpress
    labels:
      co.elastic.logs/enabled: "true"
      co.elastic.logs/json.keys_under_root: "true"
      co.elastic.logs/json.add_error_key: "true"
    restart: unless-stopped

  customer:
    build: ./services/customer
    ports:
      - "8002:8000"
    environment:
      - DEBUG=true
      - MONGODB_URI=mongodb+srv://BlueDuck2:Fcsunny0907@tpexpress.zjf26.mongodb.net/?retryWrites=true&w=majority&appName=TPExpress
      - MONGODB_DB=TPExpress
    labels:
      co.elastic.logs/enabled: "true"
      co.elastic.logs/json.keys_under_root: "true"
      co.elastic.logs/json.add_error_key: "true"
    restart: unless-stopped



