version: '3.9'

services:
  # Health service - chỉ xử lý health check
  health:
    build: ./services/health
    ports:
      - "8001:8000"
    environment:
      - DEBUG=true
    restart: unless-stopped

  # Hello service - chỉ xử lý hello world
  hello:
    build: ./services/hello
    ports:
      - "8002:8000"
    environment:
      - DEBUG=true
    restart: unless-stopped

  # Admin service - xử lý admin APIs
  admin:
    build: ./services/admin
    ports:
      - "8003:8000"
    volumes:
      # Mount data directory để persist routes.json
      - ./data:/app/data
    environment:
      - DEBUG=true
    restart: unless-stopped

  # Dynamic service - xử lý dynamic routes
  dynamic:
    build: ./services/dynamic
    ports:
      - "8004:8000"
    volumes:
      # Mount data directory để đọc routes.json
      - ./data:/app/data
    environment:
      - DEBUG=true
    restart: unless-stopped  
  
  test1:
    build: ./services/test1
    ports:
      - "8017:8000"
    environment:
      - DEBUG=true
    restart: unless-stopped  # Test5 service  # Employee service
  employee:
    build: ./services/employee
    ports:
      - "8018:8000"
    environment:
      - DEBUG=true
    restart: unless-stopped  # User service
  user:
    build: ./services/user
    ports:
      - "8019:8000"
    environment:
      - DEBUG=true
    restart: unless-stopped  # Order service
  order:
    build: ./services/order
    ports:
      - "8020:8000"
    environment:
      - DEBUG=true
      - MONGODB_URI=mongodb+srv://BlueDuck2:Fcsunny0907@tpexpress.zjf26.mongodb.net/?retryWrites=true&w=majority&appName=TPExpress
      - MONGODB_DB=test
    restart: unless-stopped
  order2:
    build: ./services/order2
    ports:
      - "8022:8000"
    environment:
      - DEBUG=true
      - MONGODB_URI=mongodb+srv://BlueDuck2:Fcsunny0907@tpexpress.zjf26.mongodb.net/?retryWrites=true&w=majority&appName=TPExpress
      - MONGODB_DB=test
    restart: unless-stopped
  order3:
    build: ./services/order3
    ports:
      - "8023:8000"
    environment:
      - DEBUG=true
    restart: unless-stopped  # Order4 service
  order4:
    build: ./services/order4
    ports:
      - "8024:8000"
    environment:
      - DEBUG=true
      - MONGODB_URI=mongodb+srv://BlueDuck2:Fcsunny0907@tpexpress.zjf26.mongodb.net/?retryWrites=true&w=majority&appName=TPExpress
      - MONGODB_DB=test
    restart: unless-stopped














 























  # Template service (khuôn mẫu để tạo services mới)
  template:
    build: ./services/template
    ports:
      - "8000:8000"
    environment:
      - DEBUG=true
    restart: unless-stopped

  order5:
    build: ./services/order5
    ports:
      - "8025:8000"
    environment:
      - DEBUG=true
      - MONGODB_URI=mongodb+srv://BlueDuck2:Fcsunny0907@tpexpress.zjf26.mongodb.net/?retryWrites=true&w=majority&appName=TPExpress
      - MONGODB_DB=test
    restart: unless-stopped

  cus:
    build: ./services/cus
    ports:
      - "8026:8000"
    environment:
      - DEBUG=true
      - MONGODB_URI=mongodb+srv://BlueDuck2:Fcsunny0907@tpexpress.zjf26.mongodb.net/?retryWrites=true&w=majority&appName=TPExpress
      - MONGODB_DB=test
    restart: unless-stopped

  date:
    build: ./services/date
    ports:
      - "8027:8000"
    environment:
      - DEBUG=true
      - MONGODB_URI=mongodb+srv://BlueDuck2:Fcsunny0907@tpexpress.zjf26.mongodb.net/?retryWrites=true&w=majority&appName=TPExpress
      - MONGODB_DB=test
    restart: unless-stopped




  # Thêm các services khác ở đây khi tạo
  # auth:
  #   build: ./services/auth
  #   ports:
  #     - "8005:8000"
  #   environment:
  #     - DEBUG=true
  #   restart: unless-stopped
  #
  # user:
  #   build: ./services/user
  #   ports:
  #     - "8006:8000"
  #   environment:
  #     - DEBUG=true
  #   restart: unless-stopped
  #
  # payment:
  #   build: ./services/payment
  #   ports:
  #     - "8007:8000"
  #   environment:
  #     - DEBUG=true
  #   restart: unless-stopped

