apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-service
  namespace: bt-api
  labels:
    app: admin-service
    service: admin
spec:
  replicas: 2
  selector:
    matchLabels:
      app: admin-service
  template:
    metadata:
      labels:
        app: admin-service
        service: admin
    spec:
      containers:
      - name: admin-service
        image: bt_api-admin:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        env:
        - name: DEBUG
          valueFrom:
            configMapKeyRef:
              name: bt-api-config
              key: DEBUG
        - name: MONGODB_URI
          value: "mongodb+srv://BlueDuck2:Fcsunny0907@tpexpress.zjf26.mongodb.net/?retryWrites=true&w=majority&appName=TPExpress"
        - name: MONGODB_DB
          value: "test"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: data-volume
          mountPath: /app/data
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: admin-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: admin-service
  namespace: bt-api
  labels:
    app: admin-service
spec:
  selector:
    app: admin-service
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: admin-data-pvc
  namespace: bt-api
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
